server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    geteway:
      router:
        - id: employeeservices
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/employee/**

eureka:
  instance:
    name: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true
